const CATEGORY_TYPES_NAMES = {
	FIRST: 'FIRST',
	SECOND: 'SECOND',
	THIRD: 'THIRD',
	FOURTH: 'FOURTH',
	FIFTH: 'FIFTH',
	SIXTH: 'SIXTH',
	SEVENTH: 'SEVENTH',
	DONE: 'DONE',
};

const CATEGORY_TYPES = [
	CATEGORY_TYPES_NAMES.FIRST,
	CATEGORY_TYPES_NAMES.SECOND,
	CATEGORY_TYPES_NAMES.THIRD,
	CATEGORY_TYPES_NAMES.FOURTH,
	CATEGORY_TYPES_NAMES.FIFTH,
	CATEGORY_TYPES_NAMES.SIXTH,
	CATEGORY_TYPES_NAMES.SEVENTH,
	CATEGORY_TYPES_NAMES.DONE,
];

const CATEGORY_TYPES_FREQUENCY = {
	[CATEGORY_TYPES_NAMES.FIRST]: 1,
	[CATEGORY_TYPES_NAMES.SECOND]: 2,
	[CATEGORY_TYPES_NAMES.THIRD]: 4,
	[CATEGORY_TYPES_NAMES.FOURTH]: 8,
	[CATEGORY_TYPES_NAMES.FIFTH]: 16,
	[CATEGORY_TYPES_NAMES.SIXTH]: 32,
	[CATEGORY_TYPES_NAMES.SEVENTH]: 64,
};

const CARD_ERROR_MESSAGES = {
	QUESTION_AND_ANSWER_REQUIRED: 'question and answer are required',
	IS_VALID_REQUIRED: 'isValid is required',
	CARD_NOT_FOUND: 'card not found',
	CARD_CANT_BE_ANSWERED_YET: "card can't be answered yet",
};

module.exports = {
	CATEGORY_TYPES_NAMES,
	CATEGORY_TYPES,
	CATEGORY_TYPES_FREQUENCY,
	CARD_ERROR_MESSAGES,
};
