const CATEGORY_TYPES = {
	FIRST: 'FIRST',
	SECOND: 'SECOND',
	THIRD: 'THIRD',
	FOURTH: 'FOURTH',
	FIFTH: 'FIFTH',
	SIXTH: 'SIXTH',
	SEVENTH: 'SEVENTH',
};

const CATEGORY_TYPES_WITH_DONE = {
	...CATEGORY_TYPES,
	DONE: 'DONE',
};

export { CATEGORY_TYPES, CATEGORY_TYPES_WITH_DONE };
